GET http://127.0.0.1:5000/api/v1/guests/publications
###

GET http://127.0.0.1:5000/api/v1/guests/publications/search?user=653d2b75d0de9404039c66b4&pet=653d3d4749b89481ab29b80e
###

GET http://127.0.0.1:5000/api/v1/users/test
###

POST http://127.0.0.1:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "jose@gmail.com",
  "password": "jose"
}
###

GET http://127.0.0.1:5000/api/v1/users/653d2b75d0de9404039c66b4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0IjoiNjUzZDJiNzVkMGRlOTQwNDAzOWM2NmI0Iiwicm9sZSI6bnVsbCwiaWF0IjoxNjk5MTU1MDY4LCJleHAiOjE2OTkxNjU4Njh9.ceg8pIgqIJvClTTFjAMQT38KLPagqpCSDkD57F7NcK0
